import {ItemSaveAction, StateFetchAction} from "@/models/actions";
import {DecisionTree, EventEdge} from "@/models/all";
import {TrueProp} from "@/models/propositions";
import {DEvents} from "./types";

export const BUILTIN_DECISION_TREES: DecisionTree<Extract<DEvents, DEvents>, Extract<DEvents, DEvents>>[] = [];

// wire up the state fetch action
BUILTIN_DECISION_TREES.push(
  new DecisionTree<DEvents.StateFetch, DEvents.None>({
    name: "[Builtin] Fetch State",
    description: "An event generated by the UI to fetch the current state from the web worker",
    edges: [
      new EventEdge<DEvents.StateFetch, DEvents.None>(
        new TrueProp(),
        new StateFetchAction(),
      )
    ],
  })
);

// wire up the ItemSave, ItemDelete, ItemEdit events to use the ItemSaveAction
BUILTIN_DECISION_TREES.push(
  new DecisionTree<DEvents.ItemNew|DEvents.ItemEdit|DEvents.ItemDelete, DEvents.None>({
    name: "[Builtin] Save Item",
    description: "Save a new item to the database",
    edges: [
      new EventEdge(
        new TrueProp(),
        new ItemSaveAction(),
      )
    ]
  })
);
