name: Pages

on:
  push:
    branches:
      - new_branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --prod

      - name: Build the site
        run: |
          # runs something like "npx next build"
          # creates the "out" directory
          yarn build
          touch out/.nojekyll

      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          name: github-pages
          path: out

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deploy pages
      id: deployment
      uses: actions/deploy-pages@v2
